---
# install tasks file for ansible-role-apf-firewall

- name: Install APF (Advanced Policy Firewall)
  apt: 
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apf-firewall
  register: my_result
  until: my_result is succeeded
  tags: apf-firewall
