---
# install tasks file for ansible-role-apf-firewall

- name: Install APF (Advanced Policy Firewall)
  apt: 
    name: {{item}}
    state: present
  with_items:
  - apf-firewall
  become: true
  tags: apf-firewall
